#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#
set -x
set -e

SCRIPT=$(readlink -f "$0")
BASEDIR=$(dirname "$SCRIPT")

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes --no-install-recommends < /stack/packages.txt
apt-get clean

#
# pipsi for simple installation of python commands
#
# NOTE: PATH=/root/.local/bin:$PATH must be set in the Dockerfile
curl --silent --retry 5 https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python

#
# MISC
#
pipsi install mercurial
pipsi install pip-tools
pipsi install supervisor
pipsi install start


# install forego (a foreman clone in go)
# TODO: remove once not needed anymore. Currently aldryn-django uses forego to
#       launch pagespeed sites with separate nginx and django processes.
curl --silent --show-error --retry 5 -o /usr/local/bin/forego https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego
chmod u+x /usr/local/bin/forego

# cleanup
rm -rf /var/lib/apt/lists/*
apt-get clean

# workaround for a bug in hub.docker.com
ln -s -f /bin/true /usr/bin/chfn

# install custom commands
cp ${BASEDIR}/run-forest-run /usr/local/bin/run-forest-run

# default virtualenv
# NOTE: PATH=/virtualenv/bin:$PATH must be set in the Dockerfile
virtualenv --no-site-packages /virtualenv
