#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# MISC
#

# install latest pip
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7

# cleanup
rm -rf /var/lib/apt/lists/*
apt-get clean

# make node available with its default name
ln -s /usr/bin/nodejs /usr/bin/node

